server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://82.156.30.3:3306/local_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: tencent7890
    type: com.alibaba.druid.pool.DruidDataSource

